name: "cppcheck code analysis"
on:
  pull_request_target:

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Perform cppcheck analysis
      uses: ikerexxe/action-cppcheck@configure_options
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        pull_request_id: ${{ github.event.pull_request.number }}
        allow_approve: false
        enable_checks: "warning,unusedFunction,missingInclude"
